baseURL = "https://go-filesystems.github.io/"
[languages.en]
  weight = 1
title = "go-filesystems"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "404"]

[markup.goldmark.renderer]
  unsafe = true
